### ISSUE TITLE
Reusing fragments between several queries

### ISSUE THREAD

**Issue by MargaretKrutikova** [Zaid-Ajaj/Snowflaqe#10]
It would be nice to be able to define fragments in separate `.gql` files and then use them across several queries and mutations. However, if a `.gql` file contains only fragment, I get an error "No query was provided".

Is there a way to use fragments with `snowflaqe` so that it can generate a shared type in `F#` and then use it in other types for queries?

**Comment by Zaid-Ajaj** [comment]
Hi @MargaretKrutikova, 

> Is there a way to use fragments with snowflaqe so that it can generate a shared type in F# and then use it in other types for queries?

No, this is quite a tricky and difficult feature for several reasons. The main one is that when fragments become their own shared type, they don't play well when being used in a query because they are *spread* and they merge with the resulting type. Right now, the fragments  are expanded immediately when they are used in a query like this:

![EXno-t_XkAAB-bJ](https://user-images.githubusercontent.com/13316248/87401536-8c7fdc00-c5ba-11ea-9f6a-923c9337050c.jpg)

if we define the type `NameParts` as follows:
```fs
type NameParts = { firstName: string; lastName: string }
```
then what should the type of the `people` field be?
```fs
// this doesn't work, `nameParts` isn't a proper field
type People = 
  { nameParts: NameParts
    phone: string  }

// this is the correct shape but it doesn't use a shared type
type People = 
  {  firstName: string
     lastName: string
     phone: string }
```
The other problem that is less tricky is reading the `.gql` files in the right order so that the fragments become known before processing the queries.

**Comment by Zaid-Ajaj** [comment]
Hi @MargaretKrutikova, is this still a problem for you? The workaround right now is to rewrite the fragments across the queries when you need them. I can look into making fragments shared across all queries: when you define a fragment anywhere, it can be used anywhere else but then *you* will have to make sure that the fragment names are unique in all query files. I am still not sure if this is a good idea but I might investigate something like this soon

**Comment by MargaretKrutikova** [comment]
Hi! I am sorry for the late response!
No, it is not a problem for me, was just wondering if there was a way of defining fragments 🙂

**Comment by Zaid-Ajaj** [comment]
That settles it then @MargaretKrutikova :smile: if this becomes a real usability issue for Snowflaqe, I will have another look at it but for now I will be closing the issue.
