### ISSUE TITLE
Why a GraphQL endpoint rather than a schema file?

### ISSUE THREAD

**Issue by njlr** [Zaid-Ajaj/Snowflaqe#2]
Why does the tool require a running endpoint or the output of the introspection query?

Wouldn't the GraphQL schema be enough? 

This would make the build process simpler.

**Comment by Zaid-Ajaj** [comment]
> Why does the tool require a running endpoint or the output of the introspection query?

Because a lot of the times you don't have control of the schema and you only have a running GraphQL backend 

> Wouldn't the GraphQL schema be enough?

Actually, if you have you a schema file definition, then that can be your input for the `schema` configuration. Just put the schema definition in a file with a `.gql` or `.graphql` extension and point the `schema` config to that file:
```json
{
   "schema": "./schema-definition.gql" 
}  
```

**Comment by njlr** [comment]
Makes sense!

PR for the docs: https://github.com/Zaid-Ajaj/Snowflaqe/pull/5

**Comment by Zaid-Ajaj** [comment]
Fixed and the docs are now in the README
