### ISSUE TITLE
Can we make Snowflaqe as Myriad plugin?

### ISSUE THREAD

**Issue by xperiandri** [Zaid-Ajaj/Snowflaqe#41]
https://github.com/MoiraeSoftware/myriad

**Comment by Zaid-Ajaj** [comment]
Currently a non-goal of Snowflaqe because Myriad doesn't generate projects, doesn't support generating multiple projects and is limited to generating a single file. 

Please add motivation of these feature requests: 
 - Why they are needed
 - What is the added value
 - Why they are better than the current implementation

**Comment by Zaid-Ajaj** [comment]
Labeled as "won't fix" since I don't feel like maintaining and building both a CLI tool _and_ a Myriad plugin and having to keep up with its dependencies.
