### ISSUE TITLE
GraphQL files with kebab cases generate incorrect F# code

### ISSUE THREAD

**Issue by OkayX6** [Zaid-Ajaj/Snowflaqe#43]
I had a file like this:
![image](https://user-images.githubusercontent.com/1169339/116808089-31c36b00-ab61-11eb-9435-3d3a4c260fd0.png)

And the generated FS code was this (picture from my Git DIFF, can you reason about it enough?) :
![image](https://user-images.githubusercontent.com/1169339/116808187-a4344b00-ab61-11eb-9f39-74724a0cd0ba.png)

Obviously they didn't compile, so I just escaped the identifiers.

**Comment by Zaid-Ajaj** [comment]
Hi @OkayX6, thanks for filing the issue! This should be a simple fix. As a workaround (without changing the file name) you can give queries or mutations names from within the query itself which will be the name of the function in the client and the corresponding modules. Instead of 

query { }

write 

query KanbanContent { }

**Comment by Zaid-Ajaj** [comment]
Snowflaqe v1.21 is released and it fixes this issue. Please give it a try and let me how it works for you 😉
